// Autogenerated helper for wagmi/viem consumers
export type ExportedContract = { address: `0x${string}`; abi: any[]; chainId: number };
export type ExportedIndex = { chainId: number; contracts: Record<string, ExportedContract> };
